theme: minima
title: Films for the fortuitous!
author: Phorys
email: phorysity@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Feel free to watch along!

# Google Analytics
#google_analytics: G-TT1DH8V3XZ
  
# social links
github_username:  Phorys # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
